{
	"m_title":"Zigbee движок",
	"m_descr":"Активация Zigbee движка.",
	"l_port":"Порт для Zigbee платы/стика",
	"h_port":"Пример: /dev/ttyUSB1 или /dev/serial/by-id/usb-Silicon_Labs_CP2105_Dual_USB_to_UART_Bridge_Controller_012082E1-if01-port0",
	"l_speed":"Скорость порта в бит/сек (автоматически обновляется при смене скорости)",
	"l_name":"Внутреннее имя",
	"h_name":"Должно быть допустимой JS строкой. Не изменяйте, если не знаете, что делаете",
	"rl_enableAPI":"Включить Zigbee API",
	"h_enableAPI":"Обрабатывать HTTP запросы /ZigbeeAPI/* и /Zigbee/&lt;внутреннее имя zway&gt;/*",
	"rl_publicAPI":"Разрешить доступ к Zigbee API без аутентификации",
	"h_publicAPI":"Не требовать аутентификации при обработке запросов к Zigbee API",
	"rl_createVDev":"Создавать виртуальные устройства домашней автоматизации",
	"h_createVDev":"Если отключить, то Zigbee устройства будут видны только в Экспертном интерфейсе и через Zigbee API",
	"l_config":"Путь к папке с настройками config/",
	"l_translations":"Путь к папке с переводами",
	"l_zddx":"Путь к базе устройств ZDDX",
	"err_binding_start":"Невозможно запустить Zigbee движок: ",
	"err_connct":"Соединение потеряно с Zigbee устройством ID: ",
	"err_reset": "Пользователь сбросил к заводским настройкам устройство ID: ",
	"dev_btl":"Zigbee устройство ID снова доступно: ",
	"err_dev_create":"Не возможно создать vDev основанное на: ",
	"main":"main powered devices",
	"battery":"battery powered devices"
}